# Generated by Django 3.1.7 on 2023-07-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_description', models.TextField()),
                ('food_image', models.ImageField(default='', upload_to='media')),
                ('restaurants', models.ManyToManyField(to='foodapp.Restaurant')),
            ],
        ),
    ]
