# Generated by Django 3.1.7 on 2023-07-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_description',
        ),
    ]
